pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Frontend 폴더 내에서 빌드를 진행
                dir('Frontend') {
                    git url: 'https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A204.git', branch: 'develop-front-test', credentialsId: 'e92707da-8291-494e-bfdd-b2a93870460a'
                }
            }
        }

        stage('List Files for Debugging') {
            steps {
                dir('Frontend') {
                    // 디렉토리 구조 확인을 위해 파일 리스트 출력
                    sh 'ls -la'
                    sh 'ls -la front/'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Frontend/front') {
                    script {
                        // 정확한 경로로 Dockerfile 빌드
                        sh 'docker build -t my-react-app:latest -f Dockerfile .'
                    }
                }
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh 'docker stop my-react-app || true'
                    sh 'docker rm my-react-app || true'
                    sh 'docker run -d -p 8081:3000 --name my-react-app my-react-app:latest'
                }
            }
        }
    }

    post {
        always {
            echo 'Build finished'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
