# Generated by Django 4.2 on 2024-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_member_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
